version: "2"
services:
 column-db:
   container_name: column-db
   image: librairy/column-db:1.0
   restart: always
   volumes:
     - ./column-db:/var/lib/cassandra
   expose:
     - "9042"
     - "9160"
   ports:
     - "5010:8080"
     - "5011:9042"
     - "5012:9160"
   networks:
     - "db"
 document-db:
   container_name: document-db
   image: librairy/document-db:1.0
   restart: always
   volumes:
     - ./document-db:/usr/share/elasticsearch/data
   expose:
     - "9200"
     - "9300"
   ports:
     - "5020:9200"
     - "5021:9300"
   networks:
     - "db"
 graph-db:
   container_name: graph-db
   image: librairy/graph-db:1.0
   restart: always
   volumes:
     - ./graph-db:/data
   expose:
     - "7474"
   ports:
     - "5030:7474"
   networks:
     - "db"
 event-bus:
   container_name: event-bus
   image: librairy/event-bus:1.0
   restart: always
   volumes:
     - ./event-bus:/var/lib/rabbitmq
   expose:
     - "15672"
     - "5672"
   ports:
     - "5040:15672"
     - "5041:5672"
   networks:
     - "events"
networks:
 db:
 events:
