FROM rabbitmq:3-management
MAINTAINER Librairy <librairy.framework@gmail.com>

ENV RABBITMQ_DEFAULT_USER librairy
ENV RABBITMQ_DEFAULT_PASS drinventor
ENV RABBITMQ_DEFAULT_VHOST drinventor

EXPOSE 15672 5672